[package]
name = "zluda"
version = "0.0.0"
authors = ["Andrzej Janik <vosen@vosen.pl>"]
edition = "2018"

[lib]
name = "zluda"
crate-type = ["cdylib"]

[dependencies]
ptx = { path = "../ptx" }
level_zero = { path = "../level_zero" }
level_zero-sys = { path = "../level_zero-sys" }
lazy_static = "1.4"
num_enum = "0.4"
lz4 = "1.23"

[dev-dependencies]
cuda-driver-sys = "0.3.0"
paste = "1.0"