[workspace]

members = [
    "level_zero-sys",
    "level_zero",
    "spirv_tools-sys",
    "notcuda",
    #"notcuda_inject",
    #"notcuda_redirect",
    "ptx",
]

[patch.crates-io]
rspirv = { git = 'https://github.com/vosen/rspirv', rev = '0f5761918624f4a95107c14abe64946c5c5f60ce' }
spirv_headers = { git = 'https://github.com/vosen/rspirv', rev = '0f5761918624f4a95107c14abe64946c5c5f60ce' }