[package]
name = "ptx"
version = "0.0.0"
authors = ["Andrzej Janik <vosen@vosen.pl>"]
edition = "2018"

[lib]

[dependencies]
lalrpop-util = "0.18.1"
regex = "1"
rspirv = "0.6"
spirv_headers = "1.4"
quick-error = "1.2"
bit-vec = "0.6"
half ="1.6"

[build-dependencies.lalrpop]
version = "0.18.1"
features = ["lexer"]

[dev-dependencies]
level_zero-sys = { path = "../level_zero-sys" }
level_zero = { path = "../level_zero" }
spirv_tools-sys = { path = "../spirv_tools-sys" }
paste = "1.0"
