[package]
name = "zluda_inject"
version = "0.0.0"
authors = ["Andrzej Janik <vosen@vosen.pl>"]
edition = "2018"

[[bin]]
name = "zluda"
path = "src/main.rs"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["processthreadsapi", "std", "synchapi"] }
detours-sys = { path = "../detours-sys" }
clap = "2.33"
